### ISSUE TITLE
store lastSeen Data-source in the browser and use as default

### ISSUE THREAD

**Issue by francescoinfante** [Linkurious/linkurious-rest-client#102]
Requested by Airbus: 
https://secure.helpscout.net/conversation/935108357/7357/

Objective is to reopen Linkurious and to be on the latest data-source used by that browser.
Use local-storage or cookie to store this info.

# Step to validate
- Go on a Linkurious with multiple data-source
- Select non the first one
- Refresh the browser
- You should see the last data-source you selected

**Comment by francescoinfante** [comment]
@fantandrea added to 2.9 with low priority.

**Comment by francescoinfante** [comment]
@pastahito add this to the rest-client refactoring epic

**Comment by francescoinfante** [comment]
The lastSeen Data-source should be per user and not shared across them. 
E.g.: if you log out and log in with another user we pick the lastSeen data-source for that user.

**Comment by thibaultlink** [comment]
Fixed. Closing.
