### ISSUE TITLE
[models] miss properties in some interfaces

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/linkurious-rest-client#105]
@Diachk here is the list of missing things in types definitions: 

- [x] sourceKey in `IMatch`
- [x] sourceKey in `IVisualization`
- [x] right in `IVisualization`
- [ ] alternativeIds in `IDataSourceSettings | IConnectedDataSourceSettings` (I only have access to `IDataSourceSettings` that only contains readonly)
- [ ] edgeSearchEnabled in `IDataSourceSettings | IConnectedDataSourceSettings`
- [ ] strictSchema in `IDataSourceSettings | IConnectedDataSourceSettings`
- [ ] edgeProperties in `IDataSourceFeatures`

**Comment by Diachk** [comment]
@maxime-allex 
- [ ] edgeSearchEnabled in `IDataSourceSettings | IConnectedDataSourceSettings` (not sure what this is for we have canIndexEdges in data-source features for that)
- [ ] strictSchema in `IDataSourceSettings | IConnectedDataSourceSettings` (only on connected data-sources)
- [ ] edgeProperties in `IDataSourceFeatures` (does not exist anymore)

**Comment by francescoinfante** [comment]
@maxime-allex what do you mean you only have access to `dataSourceSettings`?

Anyway reverting alternativeIDs to IConnectedDataSourceSettings.

It's only available if the data-source is connected.
