### ISSUE TITLE
Regex with lookbehind is not available in Firefox

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious-rest-client#128]
**Affected version**: develop-next
**Issue**: code fails to parse in Firefox
**Cause**: Lookbehind is recent implementation and is not available in Firefox and older Chrome versions. https://bugzilla.mozilla.org/show_bug.cgi?id=1225665
**Advice**: you do not need lookbehind for such a simple use case.

Locations of the bug:
- https://github.com/Linkurious/linkurious-rest-client/blob/dc727ba78035f7d0fa36899996e6d0ec7e20b5ea/src/http/request.ts#L45
- https://github.com/Linkurious/linkurious-rest-client/blob/dc727ba78035f7d0fa36899996e6d0ec7e20b5ea/src/http/request.ts#L98

**Comment by thibaultlink** [comment]
@davidrapin I'm going to need some steps to reproduce this, not sure what and where the bug is.

**Comment by thibaultlink** [comment]
Got the steps from @Diachk . This is fixed on FF.
