### ISSUE TITLE
[Create user] conflict error not handled

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/linkurious-rest-client#136]
`POST /api/admin/users`

In case of conflict (409 status error), the rest-client doesn't take the error in charge.

**Comment by thibaultlink** [comment]
Fixed : 
![image.png](https://images.zenhubusercontent.com/5cc1b8ac4e45b82b54175429/5e2ba8e2-8128-4632-b2aa-a2ad82806419)

Closing.
