### ISSUE TITLE
expose PluginRouteOptions interface

### ISSUE THREAD

**Issue by francescoinfante** [Linkurious/linkurious-rest-client#140]
To develop plugins, it may help to expose this interface:
```
interface PluginRouteOptions {
  router: express.Router;
  configuration: PluginConfig;
  getRestClient: (req: express.Request) => RestClient;
}
```
@fantandrea

**Comment by fantandrea** [comment]
Since in the `manifest.json` I have to specify:
* the application API version `"linkuriousVersion": "2.9.0"`
* the plugin API version `"pluginApiVersion": "1.0.0"`

it would be useful to have dedicated types matching the same version I have to specify in the manifest.

**Comment by fantandrea** [comment]
Since I'll need to define my own interface for the configurations:

```js
interface PluginConfig {
    basePath: string;
    debugPort?: number;
}

interface ReplayConfig extends PluginConfig {
    counter: number;
}
```

It will be helpful to have a `generic` type for `PluginRouteOptions` so that I use my custom configurations' definition:

```js
interface PluginRouteOptions<CustomPluginConfig extends PluginConfig> {
    router: Router;
    configuration: CustomPluginConfig;
    getRestClient: (req: Request) => RestClient;
}
```

```js
module.exports = function configureRoutes(options: PluginRouteOptions<ReplayConfig>) {
}
```
