### ISSUE TITLE
Get rid of `handle()`

### ISSUE THREAD

**Issue by pastahito** [Linkurious/linkurious-rest-client#148]
PR: #147 

As of today, the way we declare the possible errors an endpoint can return is by using `handle()`, for example:
```ts
// src/api/CustomAction/index.ts
public updateCustomAction(params: IUpdateCustomActionParams) {
  return this.handle(
    UNAUTHORIZED,
    DATA_SOURCE_UNAVAILABLE,
    FORBIDDEN,
    NOT_FOUND,
    MALFORMED_CUSTOM_ACTION_TEMPLATE
  ).request<CustomAction>({
    url: '/:sourceKey/customAction/:id',
    method: 'PATCH',
    params: params
  });
}
```

We want to rewrite the above code like this:
```ts
public updateCustomAction(this: Request<CustomAction>, params: IUpdateCustomActionParams) {
  return this.request({
    errors: [
      UNAUTHORIZED,
      DATA_SOURCE_UNAVAILABLE,
      FORBIDDEN,
      NOT_FOUND,
      MALFORMED_CUSTOM_ACTION_TEMPLATE
    ],
    url: '/:sourceKey/customAction/:id',
    method: 'PATCH',
    params: params
  });
}
```

What we did was:
1. If there is a type `T` in `.request<T>(...`, then remove it and add as first parameter in the public function `this: Request<T>`
2. If there is `.handle(A, B, C, ...)`, remove it and copy its elements inside `errors` property in the request object, like `this.request({errors: [A, B, C, ...], url: ...`

Do the same for **all endpoint of the RC** in the branch of PR #147

**Comment by davidrapin** [comment]
@pastahito thank you for the clarification 👍

**Comment by mzorkany** [comment]
Refactoring to get rid of handle() is done for all the APIs
Please check the PR #147

**Comment by francescoinfante** [comment]
Done: https://github.com/Linkurious/linkurious-rest-client/pull/147
