### ISSUE TITLE
Configure group styles of all edge groups

### ISSUE THREAD

**Issue by mzorkany** [Linkurious/linkurious-rest-client#156]
As an Admin I can customize the style of all EG for a DS.

Changes in the Rest Client:
Create interface `DataSourceDefaultStyles` extends `Styles`
`interface DataSourceDefaultStyles extends Styles {edgeGroup: EdgeStyle}`

**Comment by francescoinfante** [comment]
Done: https://linkurious.atlassian.net/browse/LKE-148
