### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mlhommet** [Linkurious/linkurious-rest-client#20]
error TS2304: Cannot find name 'Promise'.

I assume that one library or typescript definition is missing in the tsconfig file ?

Context: fresh clone and install on my laptop (osx)

**Comment by trusktr** [comment]
Regarding the all-too-common "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
