### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by North-City** [Linkurious/linkurious-rest-client#737]
Seeing the example of Ogma on the official website, there are some limitations in the connection line, may I ask whether there is any future plan to add curve types, such as Bessel curve, polyline, etc., with more beautiful connection methods, and whether the connection node is the connection pile is controllable, or the connection pile can specify the direction. Thank you. Looking forward to hearing from you

**Comment by davidrapin** [comment]
@North-City hi, this repository is not directly related to Ogma. For feedback or feature requests, please use Ogma’s official support channel: https://support.linkurious.com
