### ISSUE TITLE
APIs returning nodes and edges should format items for Ogma

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/linkurious-rest-client#87]
when requesting `POST /graph/run/query`

The response of the rest client is the raw response from server. Nodes and edges are of this format : 
```js
{
  id: number;
  categories: number;
  data: {[key: string]: LKProperty},
  nodelink: {...},
  ...
}
```

but in front-end we need this format (ogma will delete everything that is not in data :

```js
{
  id: number;
  data : {
    categories: number;
    properties: {[key: string]: LKProperty},
    nodelink: {...},
    ...
  } 
}
```

There's a module VisualizationParser in rest-client with methods to return the right items to the front-end. Please check that those methods are used everytime the rest-client return nodes and edges.

**Comment by Diachk** [comment]
Cloning config was removing the transform method from the config object.
@francescoinfante please review.
