### ISSUE TITLE
Custom Actions: rest-client

### ISSUE THREAD

**Issue by pastahito** [Linkurious/linkurious-rest-client#93]
Epic: https://github.com/Linkurious/linkurious-frontend/issues/2430

Specifications: [LKE 2.9.0 - Custom Actions rest client](https://docs.google.com/document/d/13PUF77MCCsIY6KSQPBDeV2kSapUT9-kcxpRS5SucxtI/edit#heading=h.sfg6ggtqqrbm)

Pull Request: https://github.com/Linkurious/linkurious-rest-client/pull/95

**Comment by thibaultlink** [comment]
Tested and validated. Closing the issue.
