### ISSUE TITLE
Add DatasourceConfig interfaces

### ISSUE THREAD

**Issue by Diachk** [Linkurious/linkurious-rest-client#96]
Add an interface for every supported data-source configuration

TODO:

#### Add interfaces for current datasource configurations
- [x] cosmosDbConfig
- [x] janusGraphConfig
- [x] janusGraphForComposeConfig
- [x] neo4jConfig
- [x] azureSearchConfig
- [x] elasticSearchConfig
- [x] elasticSearch2Config
- [x] janusGraphSearchConfig
- [x] neo2esConfig
- [x] neo4jSearchConfig

#### Refactor RestClient methods
- [x] `Linkurious.getAppConfig` read the configuration
- [x] `AdminModule.updateConfig` update config (breaking change: `dataSourceIndex -> SourceIndex`)
- [x] `AdminModule.createDataSourceConfig` create a new datasource config

@francescoinfante please review the scope of this issue

**Comment by francescoinfante** [comment]
The following API must be refactored with Params, Response interfaces in the rest-client code in a new module called `DataSourceModule`:
- [ ] /api/status
- [ ] /api/version
- [ ] /api/dataSources
- [ ] /api/admin/source/:dataSourceIndex/connect
- [ ] /api/admin/source/:dataSource/resetDefaults
- [ ] /api/admin/source/:dataSource/setDefaults
- [ ] /api/admin/sources
- [ ] /api/admin/sources/config
- [ ] /api/admin/sources/config/:configIndex
- [ ] /api/admin/sources/data/:sourceKey

Any usage of these API in any other part of the code must be removed.

**Comment by Diachk** [comment]
💔 Breaking Changes:
- `AdminModule.updateConfig` --> `ConfigurationModule.getApplicationConfig`
- `AdminModule.updateConfig` --> `ConfigurationModule.updateApplicationConfig`
- `AdminModule.createDataSourceConfig` --> `ConfigurationModule.createDataSourceConfig`
- `AdminModule.deleteDataSourceConfig`--> `ConfigurationModule.deleteDataSourceConfig`
- `Linkurious.getSourceList` ---> `DataSourceModule.getUserDataSources`
- `AdminModule.getDataSourcesList` --> `DataSourceModule.getAdminDataSources`
- `AdminModule.connectDataSource` --> `DataSourceModule.connectDataSource`
- `AdminModule.resetDefaults` --> `DataSourceModule.resetDefaults`
- `AdminModule.setDefaults` --> `DataSourceModule.setDefaults`
- `AdminModule.deleteFullDataSource` --> `DataSourceModule.deleteDataSource`
